### ISSUE TITLE
fix: The Back button does not navigate to the previous page on the Friend's profile page

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#535]
### Describe your issue

The user isn't redirected to the previous page as expected after clicking the Back button on the Friend's profile page

### Steps to reproduce

1. Open the app as an authorized user
2. Click the Friends button on the Sidebar
3. Click the friend component
4. Click the Back button
5. Look at the page

### What was the actual result?

The user isn't redirected to the previous page as expected after clicking the Back button on the Friend's profile page

### What was the expected result?

The user is redirected to the previous page after clicking the Back button on the Friend's profile page

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by GEOFARL** [comment]
Is fixed by the #502

**Comment by maksym-hladii** [comment]
The [#502](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/issues/502) task didn't solve the issue completely:
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/ba706eb8-b2e2-493a-9496-67e27bdfc506
